testing react and added project config
AlejandroVC67/hb-react-multipage-site pull request #1
Opened 2018-03-01 21:13 UTC by AlejandroVC67

2018-03-02 14:51 UTC, andrscrrn requested changes

2018-03-02 14:51 UTC, andrscrrn commented on .gitignore
> +*.map
You don't need to ignore .css or .map files anymore. Just add what you need.

2018-03-02 14:51 UTC, andrscrrn commented on package.json
> +  "main": "webpack.common.js",
If you read the package.json documentation in NPM, the `main` key is just for when scripts are generating a file that can be imported or run. This is not the case of your project so you can delete it since you don't need it.

2018-03-02 14:51 UTC, andrscrrn commented on webpack.config.js
> +}
Can you please confirm if this file is being used? I think it is not.

2018-03-02 14:51 UTC, andrscrrn commented on src/App.js
> +    <div> Testing React</div>
In addition to this, I would like to see a component inclusion where it has css and data.

2018-03-02 14:59 UTC, AlejandroVC67 commented on webpack.config.js
> +}
It is, look
<img width="1280" alt="screen shot 2018-03-02 at 10 08 00 am" src="https://user-images.githubusercontent.com/33492742/36905028-3cf0ece2-1e00-11e8-8762-43337dcb25b2.png">

2018-03-06 15:46 UTC, andrscrrn requested changes

2018-03-06 15:46 UTC, andrscrrn commented on src/App.js
> +
Why is this component now empty?

2018-03-06 16:03 UTC, andrscrrn requested changes

2018-03-06 16:03 UTC, andrscrrn commented on src/App.js
> +    this.props = props
You don't need to do this. React to this by itself.

2018-03-06 16:03 UTC, andrscrrn commented on src/data/data.json
> +    "className": "test-div",
The data shouldn't have the className store since this is not part of the data itself.

2018-03-06 16:09 UTC, merged